plugins/redmine_people/config/routes.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
      post :bulk_edit, :bulk_update, :send_mails, :add_manager
      delete :bulk_destroy
      get 'calendar' => 'people_calendars#index'
      resources :holidays, :except => :show, :controller => :people_holidays, :as => :people_holidays
    end
    member do
      get :manager
      get :autocomplete_for_manager
      delete :destroy_avatar
      get 'tabs/:tab' => 'people#show', :as => "tabs"
      get 'load_tab' => 'people#load_tab', :as => "load_tab"
      delete "remove_subordinate" => "people#remove_subordinate" , :as => "remove_subordinate"
    end
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
    get 'tabs/:tab' => 'departments#show', :as => "tabs"
    get 'load_tab' => 'departments#load_tab', :as => "load_tab"
  end
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end

resources :people_queries

plugins/redmine_people/app/models/department.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

class Department < ActiveRecord::Base
  include Redmine::SafeAttributes
  acts_as_attachable
  unloadable
  belongs_to :head, :class_name => 'Person', :foreign_key => 'head_id'

  has_many :people_information, :class_name => "PeopleInformation", :dependent => :nullify

  if ActiveRecord::VERSION::MAJOR >= 4
    has_many :people, lambda{ uniq }, :class_name => 'Person', :through => :people_information
  else
    has_many :people, :class_name => 'Person', :through => :people_information, :uniq => true
  end

  if Redmine::VERSION.to_s < '3.0'
    acts_as_nested_set :order => 'name', :dependent => :destroy
  else
    include DepartmentNestedSet
  end

  acts_as_attachable_global

  validates_presence_of :name 
  validates_uniqueness_of :name 

  attr_accessible :name, :background, :parent_id, :head_id
  safe_attributes 'name',
    'background',
    'parent_id',
    'head_id'

  def to_s
    name
  end

  def all_childs
    Department.where("lft > ? AND rgt < ?", lft, rgt).order('lft')
  end

  def css_classes
    s = 'project'
    s << ' root' if root?
    s << ' child' if child?
    s << (leaf? ? ' leaf' : ' parent')
    s
  end

  def project
    @project ||= Project.new
  end

  def allowed_parents
    return @allowed_parents if @allowed_parents
    @allowed_parents = Department.all - self_and_descendants - [self]
    @allowed_parents << nil
  end

  def people_of_branch_department
    department_ids = (self.all_childs + [self]).map(&:id)
    Person.joins(:information).where("#{PeopleInformation.table_name}.department_id" => department_ids)
  end

  def attachments_visible?(user=User.current)
    (respond_to?(:visible?) ? visible?(user) : true) &&
    (user.allowed_people_to?(:manage_departments) || PeopleInformation.find_by_user_id(user.id).try(:department_id) == self.id)
  end

  def attachments_editable?(user=User.current)
    (respond_to?(:visible?) ? visible?(user) : true) &&
      user.allowed_people_to?(:manage_departments)
  end

  def attachments_deletable?(user=User.current)
    (respond_to?(:visible?) ? visible?(user) : true) &&
      user.allowed_people_to?(:manage_departments)
  end

  class << self
    # Yields the given block for each department with its level in the tree
    def department_tree(departments, &block)
      ancestors = []
      departments.sort_by(&:lft).each do |department|
        while (ancestors.any? && !department.is_descendant_of?(ancestors.last))
          ancestors.pop
        end
        yield department, ancestors.size
        ancestors << department
      end
    end

    def all_visible_departments
      Department.order(:name)
    end
  end
end

plugins/redmine_people/app/controllers/departments_controller.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

class DepartmentsController < ApplicationController
  unloadable

  before_filter :find_department, :except => [:index, :create, :new]
  before_filter :authorize_people, :except => [:index, :show, :load_tab, :autocomplete_for_person]
  before_filter :load_department_events, :load_department_attachments, :only => [:show, :load_tab]

  helper :attachments

  def index
    @departments = Department.all
  end

  def edit
  end

  def new
    @department = Department.new
  end

  def show
  end

  def update
    @department.safe_attributes = params[:department]

    if @department.save
      attachments = Attachment.attach_files(@department, params[:attachments])
      render_attachment_warning_if_needed(@department)

      respond_to do |format| 
        format.html { redirect_to :action => "show", :id => @department } 
        format.api  { head :ok }
      end
    else
      respond_to do |format|
        format.html { render :action => 'edit' }
        format.api  { render_validation_errors(@department) }
      end      
    end    
  end  

  def destroy
    if @department.destroy
      flash[:notice] = l(:notice_successful_delete)
      if params[:from] == 'people_settings'
        respond_to do |format|
          format.html { redirect_to :controller => "people_settings", :action => "index", :tab => "departments" }
          format.api { render_api_ok }
        end
      else
        redirect_to :action => "index"
      end
    else
      flash[:error] = l(:notice_unsuccessful_save)
    end

  end  

  def create
    @department = Department.new
    @department.safe_attributes = params[:department]

    if @department.save 
      respond_to do |format| 
        format.html { redirect_to :action => "show", :id => @department } 
        # format.html { redirect_to :controller => "people_settings", :action => "index", :tab => "departments" } 
        format.api  { head :ok }
      end
    else
      respond_to do |format|
        format.html { render :action => 'new' }
        format.api  { render_validation_errors(@department) }
      end      
    end
  end  

  def add_people
    @people = PeopleInformation.where(:user_id => params[:person_id] || params[:person_ids])
    @department.people_information << @people if request.post?
    respond_to do |format|
      format.html { redirect_to :controller => 'departments', :action => 'edit', :id => @department, :tab => 'people' }
      format.js
      format.api { render_api_ok }
    end
  end

  def remove_person
    @department.people_information.delete(PeopleInformation.find(params[:person_id])) if request.delete?
    respond_to do |format|
      format.html { redirect_to :controller => 'departments', :action => 'edit', :id => @department, :tab => 'people' }
      format.js
      format.api { render_api_ok }
    end
  end


  def autocomplete_for_person
    @people = Person.active.where(:type => 'User').not_in_department(@department).like(params[:q]).limit(100)
    render :layout => false
  end  

  def load_tab
  end

  private

  def find_department
    @department = Department.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def authorize_people
    User.current.allowed_people_to?(:manage_departments, @person) || deny_access
  end  

  def load_department_attachments
    @department_attachments = @department.attachments
  end

  def load_department_events
    events = Redmine::Activity::CrmFetcher.new(User.current, :author => @department.people_of_branch_department).events(nil, nil, :limit => 10)
    @events_by_day = events.group_by(&:event_date)
  end
end

plugins/redmine_people/app/helpers/departments_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

module DepartmentsHelper
  include PeopleHelper

  def department_tree(departments, &block)
    Department.department_tree(departments, &block)
  end

  def parent_department_select_tag(department)
    selected = department.parent if department
    # retrieve the requested parent department
    parent_id = (params[:department] && params[:department][:parent_id]) || params[:parent_id]
    if parent_id
      selected = (parent_id.blank? ? nil : Department.find(parent_id))
    end
    departments = department ? department.allowed_parents.compact : Department.all
    options = ''
    options << "<option value=''></option>"
    options << department_tree_options_for_select(departments, :selected => selected)
    content_tag('select', options.html_safe, :name => 'department[parent_id]', :id => 'department_parent_id')
  end

  def department_tree_options_for_select(departments, options = {})
    s = ''
    department_tree(departments) do |department, level|
      name_prefix = (level > 0 ? '&nbsp;' * 2 * level + '&#187; ' : '').html_safe
      tag_options = {:value => department.id}
      if department == options[:selected] || department.id == options[:selected] || (options[:selected].respond_to?(:include?) && options[:selected].include?(department))
        tag_options[:selected] = 'selected'
      else
        tag_options[:selected] = nil
      end
      tag = options[:tag] || 'option'
      tag_options.merge!(yield(department)) if block_given?
      s << content_tag(tag, name_prefix + h(department), tag_options)
    end
    s.html_safe
  end

  def department_tree_grouped_options_for_select(departments, options = {})
    content_tag('optgroup', department_tree_options_for_select(departments, options), :label => l('label_department_plural'))
  end

  def department_tree_links(departments, options = {})
    s = ''
    s << "<ul class='department-tree'>"
    s << "<li> #{link_to(l(:label_people_all), :set_filter => 1)} </li>"
    department_tree(departments) do |department, level|
      name_prefix = (level > 0 ? ('&nbsp;' * 2 * level + '&#187; ') : '')
      s << "<li>" + name_prefix + people_department_link(department , :class => "#{'selected' if @department && department == @department}")
      s << "</li>"
    end
    s << "</ul>"
    s.html_safe
  end

  def people_department_link(department, options={})
    p = {:controller => 'people',
     :action => 'index',
     :set_filter => 1,
     :fields => [:status, :department_id],
     :values => {:status => [Principal::STATUS_ACTIVE.to_s], :department_id => [department.id]},
     :operators => {:status => '=', :department_id => '='}}.merge(options)

    link_to department.name, p, options
  end

  def department_tabs
    [{:name => 'activity', :partial => 'activity', :label => l(:label_activity)},
     {:name => 'files', :partial => 'attachments', :label => l(:label_attachment_plural)}
    ]
  end

  def render_department_tabs(tabs)
    if tabs.any?
      render :partial => 'common/department_tabs', :locals => {:tabs => tabs}
    else
      content_tag 'p', l(:label_no_data), :class => "nodata"
    end
  end

end

plugins/redmine_people/app/views/departments/_activity.html.erb
<% unless @events_by_day.empty? %>
  <div id="activity">
    <% @events_by_day.keys.sort.reverse.each do |day| %>
    <h4><%= format_activity_day(day) %></h4>
    <dl>
    <% @events_by_day[day].sort {|x,y| y.event_datetime <=> x.event_datetime }.each do |e| -%>
      <dt class="<%= e.event_type %>">
      <span class="time"><%= format_time(e.event_datetime, false) %></span>
      <%= content_tag('span', h(e.project), :class => 'project') %>
      <%= link_to format_activity_title(e.event_title), e.event_url %></dt>
      <dd><span class="description"><%= format_activity_description(e.event_description) %></span>
      <span class="author"><%= link_to_user(e.event_author) if e.respond_to?(:event_author) %></span>
      </dd>
    <% end -%>
    </dl>
    <% end -%>
  </div>
<% end -%>

plugins/redmine_people/app/views/departments/_attachments.html.erb
<div id="department_files">
  <div class="contextual">
    <%= link_to l(:button_add), {}, :onclick => "$('#add_attachment_form').show(); $('#add_attachment_link').hide(); return false;", :class => 'icon icon-add', :id => 'add_attachment_link' if User.current.allowed_people_to?(:manage_departments) %>
  </div>
     <%= labelled_form_for :department, @department,
                               :url => {:action => 'update', :id => @department},
                               :html => { :multipart => true, :method => :put, :id => "add_attachment_form", :style => "display:none;" } do |f|  %>

      <fieldset>
        <%= error_messages_for 'department' %>

        <p><%=l(:label_attachment_plural)%><br /><%= render :partial => 'attachments/form', :locals => {:container => @department}%></p>
        <%= submit_tag l(:button_save) -%>   
        <%= link_to l(:button_cancel), {}, :onclick => "$('#add_attachment_form').hide(); $('#add_attachment_link').show(); return false;"  %>  
      </fieldset>
  <% end -%>
  <%= render :partial => 'attachments/links', :locals => {:attachments => @department_attachments, :options  => {:author => true, :deletable => :true}, :thumbnails => Setting.thumbnails_enabled?} %>
</div>

plugins/redmine_people/app/views/departments/_form.html.erb
<%= error_messages_for @department %>

<div class="box tabular">
<p><%= f.text_field :name, :required => true %></p>
<p><%= f.text_area :background, :rows => 5, :label => :label_people_background, :class => 'wiki-edit' %></p>
<p><%= f.select :head_id, options_for_select(Person.active.in_department(@department).order(:lastname).order(:firstname).map{|d| [d.name, d.id]}.insert(0, ['', '']), :selected => @department.head_id), :label => l(:label_department_head) %></p>
<% unless @department.allowed_parents.compact.empty? %>
    <p><%= label(:department, :parent_id, l(:field_department_parent)) %><%= parent_department_select_tag(@department) %></p>
<% end %>
</div>

plugins/redmine_people/app/views/departments/_general.html.erb
  <%= labelled_form_for @department do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>

  <%= submit_tag l(:button_save) %>
  <% end %>

plugins/redmine_people/app/views/departments/_people.html.erb
<div class="splitcontentleft">
<% if @department.people.any? %>
  <table class="list people">
    <thead><tr>
      <th><%= l(:label_user) %></th>
      <% if User.current.allowed_people_to?(:edit_people) %>
      <th style="width:15%"></th>
      <% end %>
    </tr></thead>
    <tbody>
    <% @department.people.sort.each do |person| %>
      <tr id="person-<%= person.id %>" class="<%= cycle 'odd', 'even' %>">
        <td class="person"><%= link_to_user person %></td>
        <% if User.current.allowed_people_to?(:edit_people) %>
        <td class="buttons">
          <%= delete_link url_for(:action => "remove_person", :id => @department, :person_id => person), :remote => true %>
        </td>
        <% end %>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
</div>

<div class="splitcontentright">
<% people = Person.active.where(:type => 'User').not_in_department(@department).limit(100) %>
<% if people.any? %>
  <%= form_for(@department, :remote => true, :url => {:action => "add_people", :id => @department},
               :html => {:method => :post, :class => "select-users"}) do |f| %>
    <fieldset><legend><%=l(:label_user_new)%></legend>

    <p><%= label_tag "user_search", l(:label_user_search) %><%= text_field_tag 'user_search', nil %></p>
    <%= javascript_tag "observeSearchfield('user_search', 'people', '#{ escape_javascript url_for(:action => "autocomplete_for_person", :id => @department)}')" %>

    <div id="people">
      <%= principals_check_box_tags 'person_ids[]', people %>
    </div>

    <p><%= submit_tag l(:button_add) %></p>
    </fieldset>
  <% end %>
<% end %>

</div>

plugins/redmine_people/app/views/departments/add_people.js.erb
$('#tab-content-people').html('<%= escape_javascript(render :partial => 'departments/people') %>');
<% @people.each do |person| %>
  $('#person-<%= person.id %>').effect("highlight");
<% end %>

plugins/redmine_people/app/views/departments/autocomplete_for_person.html.erb
<%= principals_check_box_tags 'person_ids[]', @people %>

plugins/redmine_people/app/views/departments/edit.html.erb
<h2><%= l(:label_department) %></h2>


<% person_tabs = [{:name => 'general', :partial => 'general', :label => :label_general},
        {:name => 'people', :partial => 'people', :label => :label_people}
        ]   %>   

<%= render_tabs person_tabs %>  

<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
<% end %>

<% content_for :sidebar do %>
    <%= render :partial => 'people/sidebar' %>
<% end %>

plugins/redmine_people/app/views/departments/index.html.erb
<%= render  :partial => "people_settings/departments" %>

<% html_title(l(:label_department_plural)) -%>

<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
<% end %>

<% content_for :sidebar do %>
    <%= render :partial => 'people/sidebar' %>
<% end %>

plugins/redmine_people/app/views/departments/load_tab.js.erb
<%
    @tab = params[:tab_name]
    @partial = params[:partial]
%>
$('#tab-placeholder-<%= @tab %>').html("<%= j(render :partial => @partial) %>");

plugins/redmine_people/app/views/departments/new.html.erb
<h2><%= l(:label_department_new) %></h2>

<%= labelled_form_for @department, :url => departments_path(@department)  do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>
  <%= submit_tag l(:button_create) %>
<% end %>

<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
<% end %>

<% content_for :sidebar do %>
    <%= render :partial => 'people/sidebar' %>
<% end %>

plugins/redmine_people/app/views/departments/remove_person.js.erb
$('#tab-content-people').html('<%= escape_javascript(render :partial => 'departments/people') %>');

plugins/redmine_people/app/views/departments/show.html.erb
<%= error_messages_for 'department' %>

<% html_title "#{l(:label_department)} ##{@department.id}: #{@department.name}" %>

<div class="contextual">
  <% if User.current.allowed_people_to?(:manage_departments) %>
    <%= link_to l(:button_edit), edit_department_path(@department), :class => 'icon icon-edit' %>
    <%= link_to l(:button_delete), department_path(@department), :confirm => l(:text_are_you_sure), :method => :delete, :class => 'icon icon-del' %>
  <% end %>
</div>

<h2><%= l(:label_department) %> #<%= @department.id %></h2>

<div class="department issue details">


  <%= avatar(@department.head, :size => "50") %>

<div class="subject">
<h3><%= @department.name %></h3>
</div>
        <p class="author">
          <%= l(:label_department_head) %>
          <%= link_to_user @department.head %>
        </p>

  <% if @department.background? || @department.attachments.any? -%>

  <% if @department.background? %>
    <p><strong><%=l(:label_people_background)%></strong></p>
    <div class="wiki">
    <%= textilizable @department, :background, :attachments => @department.attachments %>
    </div>
  <% end %>
  <% end -%>
</div>

<%= render_department_tabs department_tabs%>

<% content_for :sidebar do %>
  <div id="department_people">
    <h3><%= l(:label_people) %></h3>
    <%= render :partial => 'people/person_data', :collection => @department.people.active %>
  </div>

<% end %>

<% content_for :header_tags do %>
  <%= javascript_include_tag :redmine_people, :plugin => 'redmine_people'  %>
<% end %>