plugins/redmine_people/config/routes.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
      post :bulk_edit, :bulk_update, :send_mails, :add_manager
      delete :bulk_destroy
      get 'calendar' => 'people_calendars#index'
      resources :holidays, :except => :show, :controller => :people_holidays, :as => :people_holidays
    end
    member do
      get :manager
      get :autocomplete_for_manager
      delete :destroy_avatar
      get 'tabs/:tab' => 'people#show', :as => "tabs"
      get 'load_tab' => 'people#load_tab', :as => "load_tab"
      delete "remove_subordinate" => "people#remove_subordinate" , :as => "remove_subordinate"
    end
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
    get 'tabs/:tab' => 'departments#show', :as => "tabs"
    get 'load_tab' => 'departments#load_tab', :as => "load_tab"
  end
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end

resources :people_queries

plugins/redmine_people/app/controllers/people_settings_controller.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

class PeopleSettingsController < ApplicationController
  unloadable
  menu_item :people_settings

  layout 'admin'
  before_filter :require_admin
  before_filter :find_acl, :find_principals, :only => [:index]

  helper :departments
  helper :people
  helper :people_announcements

  def index
    @groups = Group.where(:type => 'Group').sort
    @departments = Department.all
  end

  def update
    settings = Setting.plugin_redmine_people
    settings = {} if !settings.is_a?(Hash)
    settings.merge!(params[:settings])
    Setting.plugin_redmine_people = settings
    flash[:notice] = l(:notice_successful_update)
    redirect_to :action => 'index', :tab => params[:tab]
  end

  def destroy
    PeopleAcl.delete(params[:id])
    find_acl
    find_principals
    respond_to do |format|
      format.html { redirect_to :controller => 'people_settings', :action => 'index'}
      format.js
    end
  end

  def autocomplete_for_user
    find_principals
    render :layout => false
  end

  def create
    user_ids = params[:user_ids]
    acls = params[:acls]
    user_ids.each do |user_id|
      PeopleAcl.create(user_id, acls)
    end
    find_acl
    find_principals
    respond_to do |format|
      format.html { redirect_to :controller => 'people_settings', :action => 'index', :tab => 'acl'}
      format.js
    end
  end

private

  def find_acl
    @users_acl ||= PeopleAcl.all
  end

  def find_principals
    @principals = Principal.where(:status => [Principal::STATUS_ACTIVE, Principal::STATUS_ANONYMOUS]).order('type, login, lastname ASC')
    @principals = @principals.like(params[:q]) if params[:q]
    @principals = @principals.where("id NOT IN(?)", find_acl.map(&:principal_id) ) if find_acl.any?
    @principals = @principals.limit(100)
  end

end

plugins/redmine_people/app/helpers/people_settings_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

module PeopleSettingsHelper
end

plugins/redmine_people/app/views/people_settings/_acl.html.erb
<div class="splitcontentleft">
<% if @users_acl.any? %>
  <table class="list users members">
    <thead><tr>
      <th><%= l(:label_user) %></th>
      <th><%= l(:label_permissions) %></th>
      <th style="width:15%"></th>
    </tr></thead>
    <tbody>
    <% @users_acl.each do |acl| %>
      <tr id="user-<%= acl.principal_id %>" class="<%= cycle 'odd', 'even' %>">
        <td class="user name <%= 'group' if acl.principal.is_a?(Group) %>"><%= link_to_user acl.principal %></td>
        <td class="acls">
          <span id="principal-<%= acl.principal_id %>-permissions"><%= acl.permissions.map{|a| l_or_humanize(a, :prefix => 'people_permission_') }.join(', ') %></span>


          <%= form_tag({:controller => :people_settings, :action => :create}, :remote => true,
                      :method => :post, :id => "principal-#{acl.principal_id}-permissions-form", :class => 'hol'
               ) do |f| %>
          <p>
            <% RedminePeople.available_permissions.each do |permission| %>
            <label>
              <%= check_box_tag('acls[]',
                                permission, acl.permissions.include?(permission),
                                :id => nil ) %> <%= l_or_humanize(permission, :prefix => 'people_permission_') %>
            </label><br />
            <% end %>
          </p>
          <%= hidden_field_tag 'user_ids[]', acl.principal_id, :id => nil %>
          <p>
            <%= submit_tag l(:button_save), :class => "small" %>
            <%= link_to_function(l(:button_cancel),
                                 "$('#principal-#{acl.principal_id}-permissions').show(); $('#principal-#{acl.principal_id}-permissions-form').hide(); return false;") %>
          </p>
        <% end %>


        </td>
        <td class="buttons">
          <%= link_to_function l(:button_edit),
                           "$('#principal-#{acl.principal_id}-permissions').hide(); $('#principal-#{acl.principal_id}-permissions-form').show(); return false;",
                           :class => 'icon icon-edit' %>

          <%= delete_link url_for(:controller => "people_settings", :action => "destroy",  :id => acl.principal_id ), :remote => true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
</div>

<div class="splitcontentright">

<% if @principals.any? %>
  <%= form_tag({:controller => :people_settings, :action => :create}, :remote => true,
               :method => :post, :id => "people_acl_form", :class => "select-users") do %>
    <fieldset><legend><%=l(:label_user_new)%></legend>

    <p><%= label_tag "user_search", l(:label_user_search) %><%= text_field_tag 'user_search', nil %></p>
    <%= javascript_tag "observeSearchfield('user_search', 'principals', '#{ escape_javascript url_for(:controller => :people_settings, :action => :autocomplete_for_user) }')" %>

    <div id="principals">
      <%= people_principals_check_box_tags 'user_ids[]', @principals %>
    </div>
    <p><%= l(:label_permissions) %>:
    <% RedminePeople.available_permissions.each do |role| %>
      <label>
        <%= check_box_tag 'acls[]', role %>
        <%= l_or_humanize(role, :prefix => 'people_permission_') %>
      </label>
    <% end %></p>

    <p><%= submit_tag l(:button_add) %></p>
    </fieldset>
  <% end %>
<% end %>

</div>

plugins/redmine_people/app/views/people_settings/_announcements.html.erb
<div class="contextual">
  <%= link_to l(:label_announcement_new), new_people_announcement_path,
              :class => 'icon icon-add' if User.current.allowed_people_to?(:edit_announcement)
  %>
</div>

<h2><%=l(:label_announcement_plural)%></h2>
<%= form_tag(people_settings_path, :method => :get) do %>
  <fieldset>
    <legend><%= l(:label_filter_plural) %></legend>
    <label for='status'><%= l(:field_status) %>:</label>
    <%= select_tag 'announcements_status',
      options_for_select(PeopleAnnouncement::STATUS.map{|s| [l("announcement_status_#{s}"), s]}, announcement_status),
      :class => "small", :onchange => "this.form.submit(); return false;"
    %>
    <%= hidden_field_tag 'tab', 'people_announcements', :id => nil %>
  </fieldset>
<% end %>
<% if @announcements.any? %>
  <div class="autoscroll">
    <table class="list">
      <thead>
        <tr>
          <th><%=l(:label_announcement_description)%></th>
          <th><%=l(:label_announcement_frequency)%></th>
          <th><%=l(:label_announcement_start_date)%></th>
          <th><%=l(:label_announcement_end_date)%></th>
          <th><%=l(:label_announcement_active)%></th>
          <% if User.current.allowed_people_to?(:edit_announcement) %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @announcements.each do |note| %>
          <tr class="<%= cycle("odd", "even") %>">
            <td class="name"><span><%= note.description.truncate(100) %></span></td>
            <td align="center"><%= l("frequency_#{note.frequency}") %></td>
            <td align="center"><%= format_date(note.start_date) %></td>
            <td align="center"><%= format_date(note.end_date) %></td>
            <td align="center" class='tick'><%= checked_image note.active? %></td>
            <% if User.current.allowed_people_to?(:manage_departments) %>
              <td class="buttons">
                <%= link_to(l(:button_edit), edit_people_announcement_path(note), :class => 'icon icon-edit' ) %>
                <%= link_to(l(:button_delete), people_announcement_path(note), :method => :delete, :class => 'icon icon-del') %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

plugins/redmine_people/app/views/people_settings/_departments.html.erb
<div class="contextual">
<%= link_to l(:label_department_new), {:controller => 'departments', :action => 'new'}, :class => 'icon icon-add' if User.current.allowed_people_to?(:manage_departments) %>
</div>

<h2><%=l(:label_department_plural)%></h2>

<% if @departments.any? %>
<div class="autoscroll">
<table class="list">
  <thead><tr>
  <th><%=l(:label_department)%></th>
  <th><%=l(:label_department_head)%></th>
  <% if User.current.allowed_people_to?(:manage_departments) %>
  <th></th>
  <% end %>
  </tr></thead>
  <tbody>
<% department_tree(@departments) do |department, level| %>
  <tr class="<%= cycle("odd", "even") %> <%= department.css_classes %> <%= level > 0 ? "idnt idnt-#{level}" : nil %>">
  <td class="name"><span><%= link_to department, department_path(department) %></span></td>
  <td align="center"><%= link_to_user(department.head) %></td>
  <% if User.current.allowed_people_to?(:manage_departments) %>
  <td class="buttons">
    <%= link_to(l(:button_edit), edit_department_path(department), :class => 'icon icon-edit') %>
    <%= link_to(l(:button_delete), department_path(department, :from => params[:controller]), :method => :delete, :class => 'icon icon-del') %>
  </td>
  <% end %>
  </tr>
<% end %>
  </tbody>
</table>
</div>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

plugins/redmine_people/app/views/people_settings/_general.html.erb
<%= form_tag({:controller => :people_settings, :action => :update, :id => '1', :tab => 'general'},
               :method => :put, :id => "people_acl_form") do %>
  <div class="box tabular">
  <p>
    <label for="settings_visibility"><%= l(:label_people_show_for_registered_users) %></label>
    <%= hidden_field_tag 'settings[visibility]', 0, :id => nil %>
    <%= check_box_tag 'settings[visibility]', 1, Setting.plugin_redmine_people["visibility"].to_i > 0 %>
  </p>

  <p>
    <label for="settings_edit_own_data"><%= l(:label_people_edit_own_data) %></label>
    <%= hidden_field_tag 'settings[edit_own_data]', 0, :id => nil %>
    <%= check_box_tag 'settings[edit_own_data]', 1, Setting.plugin_redmine_people['edit_own_data'].to_i > 0 %>
  </p>

  <p>
    <label><%= l(:label_people_default_group) %></label>
    <%= select_tag 'settings[default_group]', options_from_collection_for_select(@groups, :id, :name, Setting.plugin_redmine_people["default_group"]), :include_blank => true %>
  </p>

  <p>
    <label for="settings_hide_age"><%= l(:label_people_hide_age) %></label>
    <%= hidden_field_tag 'settings[hide_age]', 0, :id => nil %>
    <%= check_box_tag 'settings[hide_age]', 1, Setting.plugin_redmine_people["hide_age"].to_i > 0 %>
  </p>
  </div>
  <%= submit_tag l(:button_apply) %>
<% end %>

plugins/redmine_people/app/views/people_settings/autocomplete_for_user.html.erb
<%= principals_check_box_tags 'user_ids[]', @principals %>

plugins/redmine_people/app/views/people_settings/create.js.erb
$('#tab-content-acl').html('<%= escape_javascript(render :partial => 'people_settings/acl') %>');
hideOnLoad();
<% @users_acl.each do |acl| %>
  $('#user-<%= acl.principal_id %>').effect("highlight");
<% end %>

plugins/redmine_people/app/views/people_settings/destroy.js.erb
$('#tab-content-acl').html('<%= escape_javascript(render :partial => 'people_settings/acl') %>');
hideOnLoad();

plugins/redmine_people/app/views/people_settings/index.html.erb
<h2><%= l(:label_people_settings) %></h2>
<%= error_messages_for 'people_setting' %>

<% people_tabs = [
    {:name => 'general', :partial => 'general', :label => :label_general},
    {:name => 'acl', :partial => 'acl', :label => :label_people_acl_settings},
    {:name => 'departments', :partial => 'departments', :label => :label_department_plural}
  ]
%>

<%  people_tabs.push({:name => 'hidden', :partial => 'hidden', :label => :label_people_hidden}) if params[:hidden] %>

<%= render_tabs people_tabs %>

<% html_title(l(:label_settings), l(:label_people)) -%>