plugins/redmine_people/config/routes.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :people do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :preview_email, :avatar
      post :bulk_edit, :bulk_update, :send_mails, :add_manager
      delete :bulk_destroy
      get 'calendar' => 'people_calendars#index'
      resources :holidays, :except => :show, :controller => :people_holidays, :as => :people_holidays
    end
    member do
      get :manager
      get :autocomplete_for_manager
      delete :destroy_avatar
      get 'tabs/:tab' => 'people#show', :as => "tabs"
      get 'load_tab' => 'people#load_tab', :as => "load_tab"
      delete "remove_subordinate" => "people#remove_subordinate" , :as => "remove_subordinate"
    end
end

resources :departments do
  member do
    get :autocomplete_for_person
    post :add_people
    delete :remove_person
    get 'tabs/:tab' => 'departments#show', :as => "tabs"
    get 'load_tab' => 'departments#load_tab', :as => "load_tab"
  end
end

resources :people_settings do
  collection do
    get :autocomplete_for_user
  end
end

resources :people_queries

plugins/redmine_people/app/models/people_holiday.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

class PeopleHoliday < ActiveRecord::Base
  unloadable
  include Redmine::SafeAttributes

  validates_presence_of :name, :start_date

  attr_accessor :notify

  after_create :send_notification

  safe_attributes 'name',
                  'start_date',
                  'end_date',
                  'description',
                  'is_workday',
                  'notify'

  def safe_attributes=(attrs, user=User.current)
    return unless attrs.is_a?(Hash)

    attrs = attrs.deep_dup
    attrs = delete_unsafe_attributes(attrs, user)
    return if attrs.empty?

    # mass-assignment security bypass
    assign_attributes attrs, :without_protection => true
  end

  def due_date
    end_date || start_date
  end

  def due_date=(date)
    self.end_date = date
  end

  def self.next_holidays
    where('start_date > ? AND (is_workday = ? OR is_workday IS NULL)', Date.today, false).order('start_date ASC').first(5)
  end

  def notify?
    @notify.present?
  end

  def notify_all?
    @notify == 'all'
  end

  def notify_department
    Department.find(@notify) unless notify_all?
  end

  private

  def send_notification
    if notify?
      emails = Person.all_visible.emails if notify_all?
      emails ||= notify_department.people.emails
      Mailer.holiday_notification(self, emails).deliver if emails.present?
    end
  end
end

plugins/redmine_people/app/controllers/people_holidays_controller.rb
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

class PeopleHolidaysController < ApplicationController
  unloadable

  before_filter :check_permissions, :except => [:index]
  before_filter :find_holiday, :except => [:index, :new, :create]

  def index
    raise Unauthorized unless User.current.allowed_people_to?(:view_people)
    @people_holidays = PeopleHoliday.order('start_date DESC')
  end

  def new
    @holiday = PeopleHoliday.new
  end

  def edit
  end

  def create
    @holiday = PeopleHoliday.new
    @holiday.safe_attributes = params[:holiday]
    if @holiday.save
      respond_to do |format|
        format.html {
          flash[:notice] = l(:notice_successful_create)
          redirect_to people_holidays_path
        }
      end
    else
      respond_to do |format|
        format.html {
          render :action => 'new'
        }
      end
    end
  end

  def update
    @holiday.safe_attributes = params[:holiday]
    if @holiday.save
      flash[:notice] = l(:notice_successful_update)
      respond_to do |format|
        format.html { redirect_to people_holidays_path }
      end
    else
      respond_to do |format|
        format.html { render "edit", :id => @holiday }
      end
    end
  end

  def destroy
    @holiday.destroy
    respond_to do |format|
      format.html { redirect_to people_holidays_path }
    end
  end

  private

  def check_permissions
    raise Unauthorized unless User.current.allowed_people_to?(:manage_calendar)
  end

  def find_holiday
    @holiday = PeopleHoliday.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

plugins/redmine_people/app/helpers/people_holidays_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine People (redmine_people) plugin,
# humanr resources management plugin for Redmine
#
# Copyright (C) 2011-2017 RedmineUP
# http://www.redmineup.com/
#
# redmine_people is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_people is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_people.  If not, see <http://www.gnu.org/licenses/>.

module PeopleHolidaysHelper
  include PeopleHelper
  include DepartmentsHelper

  def retrieve_people_holidays_query
    if params[:query_id].present?
      @query = PeopleHolidayQuery.find(params[:query_id])
      raise ::Unauthorized unless @query.visible?
      session[:people_holidays_query] = {:id => @query.id}
      sort_clear
    elsif api_request? || params[:set_filter] || session[:people_holidays_query].nil?
      # Give it a name, required to be valid
      @query = PeopleHolidayQuery.new(:name => "_")
      @query.build_from_params(params)
      session[:people_holidays_query] = {:filters => @query.filters, :group_by => @query.group_by, :column_names => @query.column_names}
    else
      # retrieve from session
      @query = PeopleHolidayQuery.find(session[:people_holidays_query][:id]) if session[:people_holidays_query][:id]
      @query ||= PeopleHolidayQuery.new(:name => "_", :filters => session[:people_holidays_query][:filters], :group_by => session[:people_holidays_query][:group_by], :column_names => session[:people_holidays_query][:column_names])
    end
  end

  def notify_options_for_select
    selected = params[:holiday][:notify] rescue ''
    options_for_select([['', ''], [l('label_all').humanize, 'all']], selected) << department_tree_grouped_options_for_select(Department.all_visible_departments, :selected => selected.to_i)
  end
end

plugins/redmine_people/app/views/people_holidays/_form.html.erb
<%= labelled_fields_for :holiday, @holiday do |f| %>

    <div class="splitcontent">
      <div class="splitcontentleft">
        <p><%= f.text_field :name, :label => l(:label_people_holiday_name), :size => 20, :maxlength => 255, :required => true %></p>

        <p><%= f.check_box :is_workday, :label => l(:label_people_holiday_is_workday) %></p>
      </div>
      <div class="splitcontentright">

        <p id="start_date_area">
          <%= f.text_field(:start_date, :label => l(:label_people_holiday_start_date), :size => 10, :required => true, :type => :date) %>
          <%= calendar_for('holiday_start_date') %>
        </p>

        <p id="end_date_area">
          <%= f.text_field(:end_date, :label => l(:label_people_holiday_end_date), :size => 10, :type => :date) %>
          <%= calendar_for('holiday_end_date') %>
        </p>
      </div>
    </div>

    <p>
      <%= f.label_for_field :description %>
      <%= content_tag 'span', :id => "holiday_description_and_toolbar" do %>
          <%= f.text_area :description,
                          :cols => 60,
                          :rows => (@holiday.description.blank? ? 10 : [[10, @holiday.description.length / 50].max, 100].min),
                          :accesskey => accesskey(:edit),
                          :class => 'wiki-edit',
                          :no_label => true %>
      <% end %>
    </p>
    <%= wikitoolbar_for 'holiday_description' %>

    <% if @holiday.new_record? %>
      <p><%= label_tag :notify_check, l(:label_people_holiday_notify) %><%= check_box_tag :notify_check, '1', params[:notify_check] == '1' %></p>
      <p style="display: none;"><%= f.select :notify, notify_options_for_select, :label => '' %></p>
    <% end %>

<% end %>

<%= javascript_tag do %>
    $.toggle_notify_people = function() {
      var checkbox = $('#notify_check');
      var select = $('#holiday_notify').closest('p');
      if (checkbox.is(':checked')) {
        select.show();
      } else {
        select.find('option').prop('selected', '');
        select.hide();
      }
    };

    $.toggle_notify_people();

    $('#notify_check').on('click', function() {
      $.toggle_notify_people();
    })
<% end if @holiday.new_record? %>

plugins/redmine_people/app/views/people_holidays/_next_holidays.html.erb
<table class="person_data" >
  <% PeopleHoliday.next_holidays.each do |holiday| %>
  <tr>
    <td class="name">
      <h4 class="contacts_header"><%= link_to holiday.name, calendar_people_path(:set_filter => 1, :month => holiday.start_date.month, :year => holiday.start_date.year) %></h4>
      <p><span><%= holiday.start_date.strftime('%d %B') %><%= (holiday.end_date.present? ? " - #{holiday.end_date.strftime('%d %B')}" : '' ) %></span></p>
    </td>
  </tr>
  <% end %>
</table>

plugins/redmine_people/app/views/people_holidays/edit.html.erb
<h2><%=l(:label_people_holiday_edit)%></h2>

<%= labelled_form_for @holiday, :url => people_holiday_path(@holiday),
                      :html => {:id => 'people_holiday', :multipart => true} do |f| %>
    <%= error_messages_for 'holiday' %>
    <div class="box tabular">
      <div id="all_attributes">
        <%= render :partial => 'form', :locals => {:f => f} %>
      </div>
    </div>

    <%= submit_tag l(:button_update) %>
<% end %>

<% content_for :sidebar do %>
    <%= render :partial => 'people/sidebar' %>
<% end %>

plugins/redmine_people/app/views/people_holidays/index.html.erb
<div class="contextual">
  <%= link_to l(:button_add), new_people_holiday_path, :class => 'icon icon-add' if User.current.allowed_people_to?(:manage_calendar) %>
</div>
<h2><%= l(:label_people_holidays) %></h2>
<%# unless @people_holidays.blank? %>
    <%= form_tag({}) do %>
        <div class="autoscroll" >
          <table class="list issues">
            <thead>
            <tr>
              <%= content_tag('th', h(l(:label_people_holiday_name))) %>
              <%= content_tag('th', h(l(:label_people_holiday_start_date))) %>
              <%= content_tag('th', h(l(:label_people_holiday_end_date))) %>
              <%= content_tag('th', h(l(:label_people_holiday_is_workday))) %>
              <% if User.current.allowed_people_to?(:manage_calendar) %>
              <th></th>
              <% end %>
            </tr>
            </thead>
            <tbody>
            <% @people_holidays.each do |people_holiday| %>
                <tr id="person-<%= h(people_holiday.id) %>" class="<%= cycle("odd", "even") -%>">
                  <td style="display: none;"><%= check_box_tag("ids[]", people_holiday.id, false, :id => nil) %></td>
                  <td class=""><%= people_holiday.name %></td>
                  <td class=""><%= format_date people_holiday.start_date %></td>
                  <td class=""><%= format_date people_holiday.end_date %></td>
                  <td class=""><%= people_holiday.is_workday ? l(:general_text_Yes) : l(:general_text_No) %></td>
                  <% if User.current.allowed_people_to?(:manage_calendar) %>
                  <td class="">
                    <%= link_to l(:button_edit), edit_people_holiday_path(people_holiday),
                                :class => 'icon icon-edit' %>
                    <%= link_to l(:button_delete), people_holiday_path(people_holiday),
                                :data => {:confirm => l(:text_are_you_sure)},
                                :method => :delete,
                                :class => 'icon icon-del' %>
                  </td>
                  <% end %>
                </tr>
            <% end -%>
            </tbody>
          </table>
        </div>
    <% end %>
<%# end %>

<% content_for :sidebar do %>
    <%= render :partial => 'people/sidebar' %>
<% end %>

plugins/redmine_people/app/views/people_holidays/new.html.erb
<h2><%=l(:label_people_holiday_new)%></h2>

<%= labelled_form_for @holiday, :url => people_holidays_path,
                      :html => {:id => 'people_holiday', :multipart => true} do |f| %>
    <%= error_messages_for 'holiday' %>
    <div class="box tabular">
      <div id="all_attributes">
        <%= render :partial => 'form', :locals => {:f => f} %>
      </div>
    </div>

    <%= submit_tag l(:button_create) %>
<% end %>

<% content_for :sidebar do %>
    <%= render :partial => 'people/sidebar' %>
<% end %>